<<<<<<< HEAD
import "./globals.css" 
import Navbar from "@/components/navbar/Navbar";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import Footer from "@/components/footer/Footer";
import "./globals.css" 
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import 'bootstrap/dist/css/bootstrap.min.css';
import NavbarSection from "@/components/navbar/NavbarSection";

export const metadata = {
  title: "Yol Arkaşım",
  description: "Yol Arkadaşıma Hoşgeldin!",
>>>>>>> da265e4 (Merge pull request #39 from oguzhankuzlukluoglu/oguzhan)
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="wrapper">
<<<<<<< HEAD
            <Navbar/>
            {children}
=======
            <NavbarSection/>
            {children}
            <Footer/>
>>>>>>> da265e4 (Merge pull request #39 from oguzhankuzlukluoglu/oguzhan)
          </div>
        </div>
      </body>
    </html>
  );
}
